name: Firmware Unit Tests

on:
  push:
  pull_request:

jobs:
  ceedling-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: firmware

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Ceedling
        run: gem install ceedling

      - name: Run Ceedling tests
        run: ceedling test:all